# Generated by Django 4.2.7 on 2024-01-11 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0002_alter_fooditem_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='is_vegetarian',
            field=models.BooleanField(default=True),
        ),
    ]
