# Generated by Django 4.2.7 on 2024-01-11 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0003_fooditem_is_vegetarian'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='is_vegetarian',
            field=models.CharField(max_length=100),
        ),
    ]
