# Generated by Django 4.2.7 on 2023-11-23 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='param_a',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='param_b',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='param_c',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
