# Generated by Django 4.2.7 on 2023-12-20 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user_deatils',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=255)),
                ('Task', models.CharField(max_length=255)),
                ('task_type', models.CharField(max_length=255)),
                ('Type', models.CharField(max_length=255)),
                ('Pr_prod', models.CharField(max_length=255)),
                ('clx_cat', models.CharField(max_length=255)),
                ('clocked', models.IntegerField()),
                ('minimum', models.CharField(max_length=255)),
                ('satrting_Row', models.IntegerField()),
                ('ending_Row', models.IntegerField()),
                ('Rows', models.IntegerField()),
                ('from_innerid', models.IntegerField()),
                ('end_innerid', models.IntegerField()),
                ('inner_id', models.IntegerField()),
                ('files', models.IntegerField()),
                ('file_type', models.IntegerField()),
                ('parameter', models.IntegerField()),
                ('count', models.IntegerField()),
                ('comment', models.IntegerField()),
            ],
        ),
    ]
