# Generated by Django 4.2.7 on 2023-12-20 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_deatils',
            old_name='satrting_Row',
            new_name='starting_Row',
        ),
        migrations.AlterField(
            model_name='user_deatils',
            name='file_type',
            field=models.CharField(max_length=255),
        ),
    ]
