# Generated by Django 4.2.7 on 2023-12-20 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0002_rename_satrting_row_user_deatils_starting_row_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_deatils',
            name='comment',
            field=models.CharField(max_length=255),
        ),
    ]
